# Generated by Django 4.1.2 on 2022-10-11 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('is_staffed', models.BooleanField(default=False)),
                ('title', models.CharField(choices=[('Team Lead', 'LEAD'), ('Mid Lead', 'MID'), ('Junior', 'JUN')], max_length=50)),
                ('gender', models.CharField(choices=[('Female', 'F'), ('Male', 'M'), ('Other', 'O'), ('Prefer Not Say', 'N')], max_length=50)),
                ('salary', models.IntegerField(default=1250)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='personalApp.department')),
            ],
        ),
    ]
